name: Hello
on:
  workflow_dispatch:
    inputs:
      greetings:
        type: string
        default: Hello
        required: true
        description: A cheerful word
jobs:
  run:
   runs-on: ubuntu-latest
   env:
    BRANCH: main
   steps:
     - run: echo "${{ env.BRANCH }}"